/* tslint:disable */
/* eslint-disable */
/**
 * NodeWatch API Documentation
 * API providing information about the NEM and Symbol blockchain networks,  including node and network statistics and time-series.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Node heights information, calculated as the median of the values returned by all known nodes.
 *
 * @export
 * @interface HeightInfo
 */
export interface HeightInfo {
  /**
   * Current blockchain height, as seen by the node.
   * @type {number}
   * @memberof HeightInfo
   */
  height: number;
  /**
   * Network-wide blockchain finalized height, agreed-upon by the majority of nodes.
   * @type {number}
   * @memberof HeightInfo
   */
  finalizedHeight: number;
}

/**
 * Check if a given object implements the HeightInfo interface.
 */
export function instanceOfHeightInfo(value: object): value is HeightInfo {
  if (!('height' in value) || value['height'] === undefined) return false;
  if (!('finalizedHeight' in value) || value['finalizedHeight'] === undefined) return false;
  return true;
}

export function HeightInfoFromJSON(json: any): HeightInfo {
  return HeightInfoFromJSONTyped(json, false);
}

export function HeightInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HeightInfo {
  if (json == null) {
    return json;
  }
  return {
    height: json['height'],
    finalizedHeight: json['finalizedHeight'],
  };
}

export function HeightInfoToJSON(json: any): HeightInfo {
  return HeightInfoToJSONTyped(json, false);
}

export function HeightInfoToJSONTyped(value?: HeightInfo | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    height: value['height'],
    finalizedHeight: value['finalizedHeight'],
  };
}
